name: Docker

on:
  push:
    branches:
  schedule:
    - cron: '0 7 */2 * *'

env:
  IMAGE_NAME: ghcr.io/cevo-public/cov-spectrum-website

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set environment variable "BRANCH"
        run: |
          echo "BRANCH=$(eval 'echo $GITHUB_REF | sed s/refs\\/heads\\/// | sed s/\\//__/ ')" >> $GITHUB_ENV
      - name: Build image
        run: docker build -t new_image .
      - name: Login to Github Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Add tags and push
        run: |
          docker tag new_image ${{ env.IMAGE_NAME }}:co-${{ github.sha }}
          docker push ${{ env.IMAGE_NAME }}:co-${{ github.sha }}
          docker tag new_image ${{ env.IMAGE_NAME }}:br-${{ env.BRANCH }}
          docker push ${{ env.IMAGE_NAME }}:br-${{ env.BRANCH }}
          docker tag new_image ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:latest
      - name: Add "develop" tag and push
        if: env.BRANCH == 'develop'
        run: |
          docker tag new_image ${{ env.IMAGE_NAME }}:develop
          docker push ${{ env.IMAGE_NAME }}:develop
      - name: Add "public" tag and push
        if: env.BRANCH == 'public'
        run: |
          docker tag new_image ${{ env.IMAGE_NAME }}:public
          docker push ${{ env.IMAGE_NAME }}:public
